// <auto-generated />
  namespace Rajendra.Commerce.RetailProxy.Extension
  {
  using System.CodeDom.Compiler;
  using System.IO;
  using System.Xml;

    /// <summary>
    /// Represents the EDM model.
    /// </summary>
    [GeneratedCodeAttribute("Rajendra.Commerce.RetailProxy.Extension", "1.0")]
    public class EdmModel: Microsoft.Dynamics.Commerce.RetailProxy.IEdmModelExtension
    {
        private static string edmx = "<edmx:Edmx Version=\"4.0\" xmlns:edmx=\"http://docs.oasis-open.org/odata/ns/edmx\">\r\n" +
    "  <edmx:DataServices>\r\n    <Schema Namespace=\"Microsoft.Dynamics.Retail.RetailSe" +
    "rverLibrary\" xmlns=\"http://docs.oasis-open.org/odata/ns/edm\">\r\n      <Action Nam" +
    "e=\"GetStoreHoursByRecIdFromCommonProject\" IsBound=\"true\">\r\n        <Parameter Na" +
    "me=\"bindingParameter\" Type=\"Collection(Runtime.Extension.StoreHours.Entities.Raj" +
    "StoreDayHoursEntity)\" />\r\n        <Parameter Name=\"storeNumber\" Type=\"Edm.String" +
    "\" />\r\n        <ReturnType Type=\"Collection(Runtime.Extension.StoreHours.Entities" +
    ".RajStoreDayHoursEntity)\" />\r\n      </Action>\r\n      <Function Name=\"GetMyNameFr" +
    "omCommonProject\" IsBound=\"true\">\r\n        <Parameter Name=\"bindingParameter\" Typ" +
    "e=\"Collection(Runtime.Extension.StoreHours.Entities.RajStoreDayHoursEntity)\" />\r" +
    "\n        <ReturnType Type=\"Edm.String\" />\r\n      </Function>\r\n      <Function Na" +
    "me=\"GetSampleForBooleanFromCommonProject\" IsBound=\"true\">\r\n        <Parameter Na" +
    "me=\"bindingParameter\" Type=\"Collection(Runtime.Extension.StoreHours.Entities.Raj" +
    "StoreDayHoursEntity)\" />\r\n        <ReturnType Type=\"Edm.Boolean\" Nullable=\"false" +
    "\" />\r\n      </Function>\r\n      <Action Name=\"RajSamplePostFromCommonProject\">\r\n " +
    "       <ReturnType Type=\"Edm.Boolean\" Nullable=\"false\" />\r\n      </Action>\r\n    " +
    "  <Function Name=\"RajSampleGetFromCommonProject\">\r\n        <ReturnType Type=\"Edm" +
    ".Boolean\" Nullable=\"false\" />\r\n      </Function>\r\n      <EntityContainer Name=\"C" +
    "ommerceContext\">\r\n        <EntitySet Name=\"RajendraEntityAPI\" EntityType=\"Runtim" +
    "e.Extension.StoreHours.Entities.RajStoreDayHoursEntity\" />\r\n        <ActionImpor" +
    "t Name=\"RajSamplePostFromCommonProject\" Action=\"Microsoft.Dynamics.Retail.Retail" +
    "ServerLibrary.RajSamplePostFromCommonProject\" />\r\n        <FunctionImport Name=\"" +
    "RajSampleGetFromCommonProject\" Function=\"Microsoft.Dynamics.Retail.RetailServerL" +
    "ibrary.RajSampleGetFromCommonProject\" IncludeInServiceDocument=\"true\" />\r\n      " +
    "</EntityContainer>\r\n    </Schema>\r\n    <Schema Namespace=\"Runtime.Extension.Stor" +
    "eHours.Entities\" xmlns=\"http://docs.oasis-open.org/odata/ns/edm\">\r\n      <Entity" +
    "Type Name=\"RajStoreDayHoursEntity\">\r\n        <Key>\r\n          <PropertyRef Name=" +
    "\"Id\" />\r\n        </Key>\r\n        <Property Name=\"DayOfWeek\" Type=\"Edm.Int32\" Nul" +
    "lable=\"false\" />\r\n        <Property Name=\"OpenTime\" Type=\"Edm.Int32\" Nullable=\"f" +
    "alse\" />\r\n        <Property Name=\"CloseTime\" Type=\"Edm.Int32\" Nullable=\"false\" /" +
    ">\r\n        <Property Name=\"Id\" Type=\"Edm.Int64\" Nullable=\"false\" />\r\n        <Pr" +
    "operty Name=\"ExtensionProperties\" Type=\"Collection(Microsoft.Dynamics.Commerce.R" +
    "untime.DataModel.CommerceProperty)\" />\r\n      </EntityType>\r\n    </Schema>\r\n  </" +
    "edmx:DataServices>\r\n</edmx:Edmx>";
        private static string apiVersion = "7.3";
        private static System.Collections.Generic.Dictionary<System.Type, string> proxyTypeToRuntimeTypeNameMap = new System.Collections.Generic.Dictionary<System.Type, string>()
        {
        
            { typeof(Rajendra.Commerce.RetailProxy.Extension.RajStoreDayHoursEntity), "Runtime.Extension.StoreHours.Entities.RajStoreDayHoursEntity" }
        };
        private static System.Collections.Generic.Dictionary<string, System.Type> runtimeTypeNameToProxyTypeMap = new System.Collections.Generic.Dictionary<string, System.Type>()
        {
        
            { "Runtime.Extension.StoreHours.Entities.RajStoreDayHoursEntity", typeof(Rajendra.Commerce.RetailProxy.Extension.RajStoreDayHoursEntity) }
        };
        
        /// <summary>
        /// Gets the EDMX string.
        /// </summary>
        public string Edmx
        {
            get
            {
                return edmx;
            }
        }

        /// <summary>
        /// Gets the matched Retail Server API version.
        /// </summary>
        public string ApiVersion
        {
            get
            {
                return apiVersion;
            }
        }
        
        /// <summary>
        /// Gets the map from retail proxy type to commerce runtime type names.
        /// </summary>
        public System.Collections.Generic.Dictionary<System.Type, string> ProxyTypeToRuntimeTypeNameMap
        {
            get { return proxyTypeToRuntimeTypeNameMap; }
        }

        /// <summary>
        /// Gets the map from commerce runtime type names to retail proxy type.
        /// </summary>
        public System.Collections.Generic.Dictionary<string, System.Type> RuntimeTypeNameToProxyTypeMap
        {
            get { return runtimeTypeNameToProxyTypeMap; }
        }
    }
}
