// <auto-generated />
namespace Rajendra.Commerce.RetailProxy.Extension
{
    using System;
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using Microsoft.Dynamics.Commerce.RetailProxy;
    using Microsoft.Dynamics.Commerce.RetailProxy.Adapters;
    using Microsoft.OData.Client;
    
    /// <summary>
    /// RajStoreDayHoursEntity entity class.
    /// </summary>
    [Microsoft.OData.Client.Key("Id")]
    [GeneratedCodeAttribute("Rajendra.Commerce.RetailProxy.Extension", "1.0")]
    public class RajStoreDayHoursEntity : CommerceEntity
    { 
        /// 
        /// Initializes a new instance of the <see cref="RajStoreDayHoursEntity" /> class.
        /// 
        public RajStoreDayHoursEntity()
        {
            
            this._extensionProperties.CollectionChanged += ExtensionProperties_OnCollectionChanged;
        }
      
        /// <summary>
        /// Gets or sets the DayOfWeek.
        /// </summary>
        public int DayOfWeek
        {
            get
            {
                return this._dayOfWeek;
            }
        
            set
            {
                this._dayOfWeek = value;
                this.OnPropertyChanged("DayOfWeek");
            }
        }
      
        private int _dayOfWeek;
      
        /// <summary>
        /// Gets or sets the OpenTime.
        /// </summary>
        public int OpenTime
        {
            get
            {
                return this._openTime;
            }
        
            set
            {
                this._openTime = value;
                this.OnPropertyChanged("OpenTime");
            }
        }
      
        private int _openTime;
      
        /// <summary>
        /// Gets or sets the CloseTime.
        /// </summary>
        public int CloseTime
        {
            get
            {
                return this._closeTime;
            }
        
            set
            {
                this._closeTime = value;
                this.OnPropertyChanged("CloseTime");
            }
        }
      
        private int _closeTime;
      
        /// <summary>
        /// Gets or sets the Id.
        /// </summary>
        public long Id
        {
            get
            {
                return this._id;
            }
        
            set
            {
                this._id = value;
                this.OnPropertyChanged("Id");
            }
        }
      
        private long _id;
      
        /// <summary>
        /// Gets or sets the ExtensionProperties.
        /// </summary>
        public ObservableCollection<CommerceProperty> ExtensionProperties
        {
            get
            {
                return this._extensionProperties;
            }
        
            set
            {
                this._extensionProperties = value;
                this.OnPropertyChanged("ExtensionProperties");
            }
        }
      
        private void ExtensionProperties_OnCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnPropertyChanged("ExtensionProperties");  
        }
    
        private ObservableCollection<CommerceProperty> _extensionProperties = new ObservableCollection<CommerceProperty>();
      
    }
    
}
  