// <auto-generated />
namespace Rajendra.Commerce.RetailProxy.Extension.Adapters
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.IO;
    using System.Threading.Tasks;

    
    /// <summary>
    /// Interface for Store Operations Manager.
    /// </summary>
    [GeneratedCodeAttribute("Rajendra.Commerce.RetailProxy.Extension", "1.0")]
    public interface IStoreOperationsManager : Microsoft.Dynamics.Commerce.RetailProxy.IEntityManager
    {
        
        /// <summary>
        /// RajSamplePost method.
        /// </summary>
        /// <returns>bool object.</returns>
        Task<bool> RajSamplePost();
    
        /// <summary>
        /// RajSampleGet method.
        /// </summary>
        /// <returns>bool object.</returns>
        Task<bool> RajSampleGet();
    
    }
    
    /// <summary>
    /// Interface for RajStoreDayHoursEntity Manager.
    /// </summary>
    [GeneratedCodeAttribute("Rajendra.Commerce.RetailProxy.Extension", "1.0")]
    public interface IRajStoreDayHoursEntityManager : Microsoft.Dynamics.Commerce.RetailProxy.IEntityManager
    {
        
        /// <summary>
        /// GetStoreHoursByRecId method.
        /// </summary>
        /// <param name="storeNumber">The storeNumber.</param>
        /// <param name="queryResultSettings">The queryResultSettings.</param>
        /// <returns>Collection of Runtime.Extension.StoreHours.Entities.RajStoreDayHoursEntity.</returns>
        Task<Microsoft.Dynamics.Commerce.Runtime.PagedResult<Runtime.Extension.StoreHours.Entities.RajStoreDayHoursEntity>> GetStoreHoursByRecId(string storeNumber, Microsoft.Dynamics.Commerce.Runtime.DataModel.QueryResultSettings queryResultSettings = null);
    
        /// <summary>
        /// GetMyName method.
        /// </summary>
        /// <returns>string object.</returns>
        Task<string> GetMyName();
    
        /// <summary>
        /// GetSampleForBoolean method.
        /// </summary>
        /// <returns>bool object.</returns>
        Task<bool> GetSampleForBoolean();
    
    }
    
 }
